# Numpy Continued (Follow Along)

### [ENTER]

In [1]:
import numpy as np

In [4]:
arr1d = np.array([2, 4, 6, 8])
arr1d

array([2, 4, 6, 8])

In [61]:
for i in arr1d:
    print(i)

2
4
6
8


In [7]:
arr3d = np.array([[[8,7], [6,5]], [[4,3], [2,1]]])

for i in arr3d:
    print(i)

[[8 7]
 [6 5]]
[[4 3]
 [2 1]]


In [9]:
for i in arr3d:
    for x in i:
        print(x)

[8 7]
[6 5]
[4 3]
[2 1]


In [8]:
for i in arr3d:
    for x in i:
        for a in x:
            print(a)

8
7
6
5
4
3
2
1


### 2.B.2 Joining arrays with concatenate()

In [11]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([11, 12, 13])

In [12]:
arr_c = np.concatenate((arr_a, arr_b))
arr_c

array([ 1,  2,  3, 11, 12, 13])

In [14]:
arr_d = np.concatenate((arr_a, arr_b), axis=0)
arr_d

array([ 1,  2,  3, 11, 12, 13])

In [18]:
arr_stacked = np.stack((arr_a, arr_b))
arr_stacked

array([[ 1,  2,  3],
       [11, 12, 13]])

In [20]:
arr_stacked2 = np.stack((arr_a, arr_b), axis=1)
arr_stacked2

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [22]:
arr_sos = np.concatenate((arr_stacked, arr_stacked))
arr_sos

array([[ 1,  2,  3],
       [11, 12, 13],
       [ 1,  2,  3],
       [11, 12, 13]])

In [23]:
arr_sos2 = np.concatenate((arr_stacked, arr_stacked), axis=1)
arr_sos2

array([[ 1,  2,  3,  1,  2,  3],
       [11, 12, 13, 11, 12, 13]])

In [24]:
arr_hstk = np.hstack((arr_stacked, arr_stacked))
arr_hstk

array([[ 1,  2,  3,  1,  2,  3],
       [11, 12, 13, 11, 12, 13]])

In [25]:
arr_vstk = np.vstack((arr_stacked, arr_stacked))
arr_vstk

array([[ 1,  2,  3],
       [11, 12, 13],
       [ 1,  2,  3],
       [11, 12, 13]])

In [26]:
arr_dstk = np.dstack((arr_stacked, arr_stacked))
arr_dstk

array([[[ 1,  1],
        [ 2,  2],
        [ 3,  3]],

       [[11, 11],
        [12, 12],
        [13, 13]]])

### 2.B.5 Splitting Arrays

In [27]:
arr_vstk

array([[ 1,  2,  3],
       [11, 12, 13],
       [ 1,  2,  3],
       [11, 12, 13]])

In [29]:
split_3way = np.array_split(arr_vstk, 3)
split_3way

[array([[ 1,  2,  3],
        [11, 12, 13]]),
 array([[1, 2, 3]]),
 array([[11, 12, 13]])]

In [30]:
split_4way = np.array_split(arr_vstk, 4)
split_4way

[array([[1, 2, 3]]),
 array([[11, 12, 13]]),
 array([[1, 2, 3]]),
 array([[11, 12, 13]])]

In [31]:
split_4_0 = np.array_split(arr_vstk, 4, axis=0)
split_4_0

[array([[1, 2, 3]]),
 array([[11, 12, 13]]),
 array([[1, 2, 3]]),
 array([[11, 12, 13]])]

In [32]:
split_4_1 = np.array_split(arr_vstk, 4, axis=1)
split_4_1

[array([[ 1],
        [11],
        [ 1],
        [11]]),
 array([[ 2],
        [12],
        [ 2],
        [12]]),
 array([[ 3],
        [13],
        [ 3],
        [13]]),
 array([], shape=(4, 0), dtype=int64)]

### 2.B.6 Using Where() To Search and Alter Arrays

In [34]:
values = np.array([4, 9, 4, 8, 0, 6])
cond1 = np.where(values < 5)
cond1

(array([0, 2, 4]),)

In [36]:
print(np.array(cond1))

[[0 2 4]]


In [40]:
cond2 = np.where(values < 5, values, values * .9)
print(cond2)

[4.  8.1 4.  7.2 0.  5.4]


In [45]:
cond3 = np.where(values < 5, values, 'over 5')
print(cond3)

['4' 'over 5' '4' 'over 5' '0' 'over 5']


In [46]:
arr_vstk

array([[ 1,  2,  3],
       [11, 12, 13],
       [ 1,  2,  3],
       [11, 12, 13]])

In [47]:
cond4 = np.where(arr_vstk > 10)
cond4

(array([1, 1, 1, 3, 3, 3]), array([0, 1, 2, 0, 1, 2]))

In [50]:
cond5 = np.where(arr_vstk > 10, 'up', 'down')
print(cond5)

[['down' 'down' 'down']
 ['up' 'up' 'up']
 ['down' 'down' 'down']
 ['up' 'up' 'up']]


### 2.B.7 Sorting Arrays

In [51]:
values

array([4, 9, 4, 8, 0, 6])

In [52]:
arr_vstk

array([[ 1,  2,  3],
       [11, 12, 13],
       [ 1,  2,  3],
       [11, 12, 13]])

In [53]:
print(np.sort(values))

[0 4 4 6 8 9]


In [54]:
print(np.sort(arr_vstk))

[[ 1  2  3]
 [11 12 13]
 [ 1  2  3]
 [11 12 13]]


In [55]:
print(np.sort(cond5))

[['down' 'down' 'down']
 ['up' 'up' 'up']
 ['down' 'down' 'down']
 ['up' 'up' 'up']]


### 2.B.8 Filtering Arrays

In [56]:
z = np.array([14, 9, 4, 18, 0, 6])
z

array([14,  9,  4, 18,  0,  6])

In [57]:
# Standard Python method

filter_z = []

for i in z:
    if i > 10:
        filter_z.append(True)
    else:
        filter_z.append(False)

print(filter_z)

[True, False, False, True, False, False]


In [58]:
# Applying boolean index

y = z[filter_z]
print(y)

[14 18]


In [59]:
x = z > 10
z_over_10 = z[x]
print(z_over_10)

[14 18]


# Section 2.C Random in NumPy

In [ ]:
h = np.random.randint(1, 200, size=