# NumPy Fundamentals

In [1]:
import numpy as np

### Array Basis

In [2]:
fruits = ['apple', 'banana', 'cherry', 'date',]

In [3]:
arr_1 = np.array([fruits])
arr_1

array([['apple', 'banana', 'cherry', 'date']], dtype='<U6')

In [4]:
arr_1 = np.array([fruits])
arr_1.dtype

dtype('<U6')

In [5]:
# A dtype result of <U6 means the most amount of characters
# any of the array's strings has is 6. Remove Banana & Cherry, 
# and it returns <U5. Remove Apple too and it returns <U4

In [6]:
arr_2 = np.array([[10, 11, 12], [13, 14, 15]])
arr_2

array([[10, 11, 12],
       [13, 14, 15]])

In [7]:
arr_2.T

array([[10, 13],
       [11, 14],
       [12, 15]])

In [8]:
# Transposing the array will basically invert its dimensions
# ...at least I think that's how it works

In [9]:
arr_3 = np.array([[1, 3, 5], [2, 4, 6]])
arr_3

array([[1, 3, 5],
       [2, 4, 6]])

In [26]:
arr_4 = arr_3[0, 2], arr_3[1, 1]
arr_4

(np.int64(5), np.int64(4))

In [ ]:
# This returns the specified values within the second dimnesion
# from arr_3, being 5 and 4 respecively

In [ ]:
arr_5