In [1]:
import numpy as np

## Looping Through Arrays

In [2]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])
arrA

array([[11, 12, 13],
       [14, 15, 16]])

In [3]:
for x in arrA:
    print(x*2)

[22 24 26]
[28 30 32]


In [4]:
for x in arrA:
    # for y in (x*2):
    for y in x:
        print(y*2)

22
24
26
28
30
32


In the first loop, we strip our array down to 2 1D elements.
In the second loop, we strip our array down to the 6 0D elements.
After which, the result for y is multiplied by 2.

In [5]:
 loop_result = []
# for x in arrA:
#     for y in x:
#         print(loop_result)

# for (loop_result) in arrA:
#     for y in (loop_result):
#         print(y)

for x in arrA:
    for y in x:
        loop_result.append(y * 2)

print(loop_result)

[np.int64(22), np.int64(24), np.int64(26), np.int64(28), np.int64(30), np.int64(32)]


## Joining & Stacking Arrays

In [6]:
joined_array_1 = np.concatenate((arrA,arrA))
joined_array_1

array([[11, 12, 13],
       [14, 15, 16],
       [11, 12, 13],
       [14, 15, 16]])

In [7]:
joined_array_2 = np.concatenate((arrA,arrA), axis=1)
joined_array_2

array([[11, 12, 13, 11, 12, 13],
       [14, 15, 16, 14, 15, 16]])

In [8]:
stacked_array_1 = np.concatenate((joined_array_1,joined_array_1))
stacked_array_1

array([[11, 12, 13],
       [14, 15, 16],
       [11, 12, 13],
       [14, 15, 16],
       [11, 12, 13],
       [14, 15, 16],
       [11, 12, 13],
       [14, 15, 16]])

In [9]:
stacked_array_2 = np.concatenate((joined_array_1,joined_array_2))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 6

In [10]:
# A value error stating that array dimensions, excluding the concat axis, should match

In [11]:
another_joined_array = np.concatenate((joined_array_1,arrA))
another_joined_array

array([[11, 12, 13],
       [14, 15, 16],
       [11, 12, 13],
       [14, 15, 16],
       [11, 12, 13],
       [14, 15, 16]])

In [12]:
another_2 = np.concatenate((joined_array_1,arrA), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [13]:
#  The same value error occures because both array's dimensions differ from each other

In [14]:
stacked_arr_h = np.hstack((arrA, arrA))
stacked_arr_h

# Stacks horizontally or along rows

array([[11, 12, 13, 11, 12, 13],
       [14, 15, 16, 14, 15, 16]])

In [15]:
stacked_arr_v = np.vstack((arrA, arrA))
stacked_arr_v

# Stacks vertically or along columns

array([[11, 12, 13],
       [14, 15, 16],
       [11, 12, 13],
       [14, 15, 16]])

In [16]:
stacked_arr_d = np.dstack((arrA, arrA))
stacked_arr_d

# Stacks along height and depth

array([[[11, 11],
        [12, 12],
        [13, 13]],

       [[14, 14],
        [15, 15],
        [16, 16]]])

## Splitting Arrays

In [17]:
splitsky = np.array_split(joined_array_1, 2)
splitsky
# Splits the input into two 2-Dimensional arrays

[array([[11, 12, 13],
        [14, 15, 16]]),
 array([[11, 12, 13],
        [14, 15, 16]])]

In [18]:
spliterino = np.array_split(joined_array_1, 3)
spliterino
# Splits the input into three 2-dimensional arrays
# First array has more values

[array([[11, 12, 13],
        [14, 15, 16]]),
 array([[11, 12, 13]]),
 array([[14, 15, 16]])]

## Searching & Replacing Array Values

In [19]:
def get_even_numbers(numbers):
    even_numbers = []
    for number in numbers:
        if number % 2 == 0:
            even_numbers.append(number)
        else:
            print('odd')
    return even_numbers

arr = np.array([11, 12, 13, 14, 15, 16])
result = get_even_numbers(arr)

print(result)

odd
odd
odd
[np.int64(12), np.int64(14), np.int64(16)]


## Filtering Arrays

In [20]:
arrB = np.array([[7,6], [13,5], [7,3]])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [21]:
z = arrB < 7
arrC = arrB[z]
print(arrC)


[6 5 3]


In [22]:
y = arrB >= 7
arrD = arrB[y]
print(arrD)


[ 7 13  7]
